"""DRF API ????擏??萄??
?謕???ｇ????Django ?賹縣??router???魂???????????????謘??????頩???? `/docs/api-routes/` ?蹓遴??????
- canonical API ????
- legacy alias ????
- ?????DRF view ?遴竣??
- ?獢????輯??????方?
"""
from __future__ import annotations

API_ROUTE_GROUPS = [
    {
        "group": "Schema",
        "routes": [
            {
                "name": "OpenAPI Schema",
                "canonical": "/api/v1/schema/",
                "legacy": "",
                "view": "drf_spectacular.views.SpectacularAPIView",
                "drf": True,
                "status": "canonical",
                "notes": "Primary OpenAPI schema endpoint for DRF-generated API docs.",
            },
            {
                "name": "Swagger UI",
                "canonical": "/api/v1/schema/swagger-ui/",
                "legacy": "",
                "view": "drf_spectacular.views.SpectacularSwaggerView",
                "drf": True,
                "status": "canonical",
                "notes": "Interactive API documentation page.",
            },
            {
                "name": "ReDoc",
                "canonical": "/api/v1/schema/redoc/",
                "legacy": "",
                "view": "drf_spectacular.views.SpectacularRedocView",
                "drf": True,
                "status": "canonical",
                "notes": "Alternative API documentation page.",
            },
        ],
    },
    {
        "group": "Catalog",
        "routes": [
            {
                "name": "Current User",
                "canonical": "/api/v1/me/",
                "legacy": "",
                "view": "myapp.api.views.MeApi",
                "drf": True,
                "status": "canonical",
                "notes": "Returns the current demo session user snapshot.",
            },
            {
                "name": "Products List",
                "canonical": "/api/v1/products/",
                "legacy": "",
                "view": "myapp.api.views.ProductListApi",
                "drf": True,
                "status": "canonical",
                "notes": "DRF catalog list with filters, sorting, and pagination.",
            },
            {
                "name": "Product Detail",
                "canonical": "/api/v1/products/<slug>/",
                "legacy": "",
                "view": "myapp.api.views.ProductDetailApi",
                "drf": True,
                "status": "canonical",
                "notes": "DRF product detail payload with variants and pricing summary.",
            },
            {
                "name": "Product Reviews",
                "canonical": "/api/v1/products/<slug>/reviews/",
                "legacy": "/api/products/<slug>/reviews/",
                "view": "myapp.api.views.ProductReviewsApi",
                "drf": True,
                "status": "aliased",
                "notes": "Legacy route now points to the same DRF review endpoint.",
            },
            {
                "name": "Product Questions",
                "canonical": "/api/v1/products/<slug>/questions/",
                "legacy": "/api/products/<slug>/questions/",
                "view": "myapp.api.views.ProductQuestionsApi",
                "drf": True,
                "status": "aliased",
                "notes": "Legacy route now points to the DRF Q&A endpoint.",
            },
            {
                "name": "Product Answers",
                "canonical": "/api/v1/products/<slug>/questions/<question_id>/answers/",
                "legacy": "/api/products/<slug>/questions/<question_id>/answers/",
                "view": "myapp.api.views.ProductAnswersApi",
                "drf": True,
                "status": "aliased",
                "notes": "Legacy answer submission now uses DRF validation and responses.",
            },
            {
                "name": "Product Recommendations",
                "canonical": "/api/v1/products/<slug>/recommendations/",
                "legacy": "/api/products/<slug>/recommendations/",
                "view": "myapp.api.views.ProductRecommendationsApi",
                "drf": True,
                "status": "aliased",
                "notes": "Legacy recommendation route now returns DRF-serialized payloads.",
            },
            {
                "name": "Product Price Compare",
                "canonical": "/api/v1/products/<slug>/price-compare/",
                "legacy": "",
                "view": "myapp.api.views.ProductPriceCompareApi",
                "drf": True,
                "status": "canonical",
                "notes": "Returns mock competitor pricing data for price-comparison demos.",
            },
            {
                "name": "Product Price Compare Refresh",
                "canonical": "/api/v1/products/<slug>/price-compare/refresh/",
                "legacy": "",
                "view": "myapp.api.views.ProductPriceCompareRefreshApi",
                "drf": True,
                "status": "canonical",
                "notes": "Simulates refreshing crawler/API price snapshots for the current product.",
            },
        ],
    },
    {
        "group": "Community",
        "routes": [
            {
                "name": "Community Posts",
                "canonical": "/api/v1/community/posts/",
                "legacy": "/api/community/posts/",
                "view": "myapp.api.views.CommunityPostsApi",
                "drf": True,
                "status": "aliased",
                "notes": "Legacy list/create route now uses DRF serializers.",
            },
            {
                "name": "Community Post Detail",
                "canonical": "/api/v1/community/posts/<post_id>/",
                "legacy": "/api/community/posts/<post_id>/",
                "view": "myapp.api.views.CommunityPostDetailApi",
                "drf": True,
                "status": "aliased",
                "notes": "Legacy post detail route now shares the DRF detail view.",
            },
            {
                "name": "Community Replies",
                "canonical": "/api/v1/community/posts/<post_id>/replies/",
                "legacy": "/api/community/posts/<post_id>/replies/",
                "view": "myapp.api.views.CommunityRepliesApi",
                "drf": True,
                "status": "aliased",
                "notes": "Legacy reply submission now uses DRF validation and response shape.",
            },
            {
                "name": "Community Vote",
                "canonical": "/api/v1/community/posts/<post_id>/vote/",
                "legacy": "/api/community/posts/<post_id>/vote/",
                "view": "myapp.api.views.CommunityVoteApi",
                "drf": True,
                "status": "aliased",
                "notes": "Legacy vote route now uses DRF permissions and serializer-based response.",
            },
        ],
    },
    {
        "group": "Account",
        "routes": [
            {
                "name": "Dashboard Summary",
                "canonical": "/api/v1/me/dashboard/",
                "legacy": "",
                "view": "myapp.api.views.MeDashboardApi",
                "drf": True,
                "status": "canonical",
                "notes": "Buyer/member center summary for favorites, recent views, orders, and owned content.",
            },
            {
                "name": "Favorite Toggle",
                "canonical": "/api/v1/products/<slug>/favorite/",
                "legacy": "",
                "view": "myapp.api.views.FavoriteToggleApi",
                "drf": True,
                "status": "canonical",
                "notes": "Session-backed favorite toggle exposed through DRF.",
            },
            {
                "name": "Compare Toggle",
                "canonical": "/api/v1/products/<slug>/compare/",
                "legacy": "",
                "view": "myapp.api.views.CompareToggleApi",
                "drf": True,
                "status": "canonical",
                "notes": "Session-backed compare list toggle exposed through DRF.",
            },
            {
                "name": "Address Book",
                "canonical": "/api/v1/me/addresses/",
                "legacy": "",
                "view": "myapp.api.views.MeAddressesApi",
                "drf": True,
                "status": "canonical",
                "notes": "List and create buyer shipping addresses.",
            },
            {
                "name": "Address Default",
                "canonical": "/api/v1/me/addresses/<address_id>/default/",
                "legacy": "",
                "view": "myapp.api.views.MeAddressDefaultApi",
                "drf": True,
                "status": "canonical",
                "notes": "Set one address as the buyer default address.",
            },
            {
                "name": "Address Delete",
                "canonical": "/api/v1/me/addresses/<address_id>/",
                "legacy": "",
                "view": "myapp.api.views.MeAddressDeleteApi",
                "drf": True,
                "status": "canonical",
                "notes": "Delete one buyer address via DRF.",
            },
            {
                "name": "Invoice Profile",
                "canonical": "/api/v1/me/invoice/",
                "legacy": "",
                "view": "myapp.api.views.MeInvoiceApi",
                "drf": True,
                "status": "canonical",
                "notes": "Read and update invoice preferences.",
            },
        ],
    },
    {
        "group": "Orders",
        "routes": [
            {
                "name": "Buyer Orders",
                "canonical": "/api/v1/me/orders/",
                "legacy": "",
                "view": "myapp.api.views.BuyerOrdersApi",
                "drf": True,
                "status": "canonical",
                "notes": "List current buyer orders with shipment groups and after-sales state.",
            },
            {
                "name": "Buyer Order Detail",
                "canonical": "/api/v1/me/orders/<order_id>/",
                "legacy": "",
                "view": "myapp.api.views.BuyerOrderDetailApi",
                "drf": True,
                "status": "canonical",
                "notes": "Return one buyer order detail via DRF.",
            },
            {
                "name": "Buyer Cancel Request",
                "canonical": "/api/v1/me/orders/<order_id>/cancel-request/",
                "legacy": "",
                "view": "myapp.api.views.BuyerCancelRequestApi",
                "drf": True,
                "status": "canonical",
                "notes": "Create a buyer-side cancellation request through DRF.",
            },
            {
                "name": "Buyer Refund Request",
                "canonical": "/api/v1/me/orders/<order_id>/refund-request/",
                "legacy": "",
                "view": "myapp.api.views.BuyerRefundRequestApi",
                "drf": True,
                "status": "canonical",
                "notes": "Create a buyer-side refund request through DRF.",
            },
        ],
    },
    {
        "group": "Seller / Admin",
        "routes": [
            {
                "name": "Seller Orders",
                "canonical": "/api/v1/me/sales/",
                "legacy": "",
                "view": "myapp.api.views.SellerOrdersApi",
                "drf": True,
                "status": "canonical",
                "notes": "List seller-scoped orders with date filters.",
            },
            {
                "name": "Seller Order Detail",
                "canonical": "/api/v1/me/sales/<order_id>/",
                "legacy": "",
                "view": "myapp.api.views.SellerOrderDetailApi",
                "drf": True,
                "status": "canonical",
                "notes": "Return only the current seller's lines for one order.",
            },
            {
                "name": "Seller Order Update",
                "canonical": "/api/v1/me/sales/<order_id>/update/",
                "legacy": "",
                "view": "myapp.api.views.SellerOrderUpdateApi",
                "drf": True,
                "status": "canonical",
                "notes": "Update seller fulfillment status, tracking code, and shipment note.",
            },
            {
                "name": "Seller Sales Report",
                "canonical": "/api/v1/me/sales/report/",
                "legacy": "",
                "view": "myapp.api.views.SellerSalesReportApi",
                "drf": True,
                "status": "canonical",
                "notes": "Return seller revenue summary and top-selling products.",
            },
            {
                "name": "Admin Dashboard",
                "canonical": "/api/v1/staff/dashboard/",
                "legacy": "",
                "view": "myapp.api.views.AdminDashboardApi",
                "drf": True,
                "status": "canonical",
                "notes": "Platform-wide summary for users, products, orders, and service requests.",
            },
            {
                "name": "Admin Orders",
                "canonical": "/api/v1/staff/orders/",
                "legacy": "",
                "view": "myapp.api.views.AdminOrdersApi",
                "drf": True,
                "status": "canonical",
                "notes": "List orders for admin review with filters.",
            },
            {
                "name": "Admin Order Detail",
                "canonical": "/api/v1/staff/orders/<order_id>/",
                "legacy": "",
                "view": "myapp.api.views.AdminOrderDetailApi",
                "drf": True,
                "status": "canonical",
                "notes": "Return one order with service request details for admin review.",
            },
            {
                "name": "Admin Service Review",
                "canonical": "/api/v1/staff/orders/<order_id>/service-review/",
                "legacy": "",
                "view": "myapp.api.views.AdminOrderServiceReviewApi",
                "drf": True,
                "status": "canonical",
                "notes": "Approve or reject cancellation/refund requests.",
            },
            {
                "name": "Admin Users",
                "canonical": "/api/v1/staff/users/",
                "legacy": "",
                "view": "myapp.api.views.AdminUsersApi",
                "drf": True,
                "status": "canonical",
                "notes": "List users for admin management and search.",
            },
            {
                "name": "Admin User Status Update",
                "canonical": "/api/v1/staff/users/<username>/status/",
                "legacy": "",
                "view": "myapp.api.views.AdminUserStatusApi",
                "drf": True,
                "status": "canonical",
                "notes": "Suspend or reactivate a demo user account.",
            },
        ],
    },
    {
        "group": "Wave 3: Auth / Cart / Seller Tools",
        "routes": [
            {
                "name": "Login",
                "canonical": "/api/v1/auth/login/",
                "legacy": "",
                "view": "myapp.api.views.LoginApi",
                "drf": True,
                "status": "canonical",
                "notes": "Demo session login endpoint.",
            },
            {
                "name": "Register",
                "canonical": "/api/v1/auth/register/",
                "legacy": "",
                "view": "myapp.api.views.RegisterApi",
                "drf": True,
                "status": "canonical",
                "notes": "Demo session registration endpoint.",
            },
            {
                "name": "Logout",
                "canonical": "/api/v1/auth/logout/",
                "legacy": "",
                "view": "myapp.api.views.LogoutApi",
                "drf": True,
                "status": "canonical",
                "notes": "Demo session logout endpoint.",
            },
            {
                "name": "Profile Update",
                "canonical": "/api/v1/me/profile/",
                "legacy": "",
                "view": "myapp.api.views.MeProfileApi",
                "drf": True,
                "status": "canonical",
                "notes": "Update the current member profile.",
            },
            {
                "name": "Seller Request",
                "canonical": "/api/v1/me/seller-request/",
                "legacy": "",
                "view": "myapp.api.views.SellerRequestApi",
                "drf": True,
                "status": "canonical",
                "notes": "Submit a seller access request.",
            },
            {
                "name": "Cart Snapshot",
                "canonical": "/api/v1/cart/",
                "legacy": "",
                "view": "myapp.api.views.CartApi",
                "drf": True,
                "status": "canonical",
                "notes": "Read cart snapshot and apply / clear coupon code.",
            },
            {
                "name": "Cart Add Item",
                "canonical": "/api/v1/cart/items/",
                "legacy": "",
                "view": "myapp.api.views.CartAddApi",
                "drf": True,
                "status": "canonical",
                "notes": "Add one item into the session-backed cart.",
            },
            {
                "name": "Cart Item Update/Delete",
                "canonical": "/api/v1/cart/items/<item_key>/",
                "legacy": "",
                "view": "myapp.api.views.CartItemApi",
                "drf": True,
                "status": "canonical",
                "notes": "Update quantity or delete one cart line.",
            },
            {
                "name": "Checkout Preview",
                "canonical": "/api/v1/checkout/preview/",
                "legacy": "",
                "view": "myapp.api.views.CheckoutPreviewApi",
                "drf": True,
                "status": "canonical",
                "notes": "Return checkout preview data without creating an order.",
            },
            {
                "name": "Checkout Confirm",
                "canonical": "/api/v1/checkout/confirm/",
                "legacy": "",
                "view": "myapp.api.views.CheckoutConfirmApi",
                "drf": True,
                "status": "canonical",
                "notes": "Create an order from the current cart.",
            },
            {
                "name": "Seller Products",
                "canonical": "/api/v1/me/products/",
                "legacy": "",
                "view": "myapp.api.views.SellerProductsApi",
                "drf": True,
                "status": "canonical",
                "notes": "List or create seller-owned products.",
            },
            {
                "name": "Seller Product Detail",
                "canonical": "/api/v1/me/products/<slug>/",
                "legacy": "",
                "view": "myapp.api.views.SellerProductDetailApi",
                "drf": True,
                "status": "canonical",
                "notes": "Read, update, or delete one seller product.",
            },
            {
                "name": "Seller Product Archive",
                "canonical": "/api/v1/me/products/<slug>/archive/",
                "legacy": "",
                "view": "myapp.api.views.SellerProductArchiveApi",
                "drf": True,
                "status": "canonical",
                "notes": "Archive one seller product.",
            },
            {
                "name": "Seller Product Duplicate",
                "canonical": "/api/v1/me/products/<slug>/duplicate/",
                "legacy": "",
                "view": "myapp.api.views.SellerProductDuplicateApi",
                "drf": True,
                "status": "canonical",
                "notes": "Duplicate one seller product as a new draft.",
            },
            {
                "name": "Staff Review Dashboard",
                "canonical": "/api/v1/staff/reviews/",
                "legacy": "",
                "view": "myapp.api.views.StaffReviewDashboardApi",
                "drf": True,
                "status": "canonical",
                "notes": "Return seller request queue and currently active products for moderation.",
            },
            {
                "name": "Seller Request Review",
                "canonical": "/api/v1/staff/seller-requests/<username>/review/",
                "legacy": "",
                "view": "myapp.api.views.SellerRequestReviewApi",
                "drf": True,
                "status": "canonical",
                "notes": "Approve or reject one seller access request.",
            },
            {
                "name": "Product Force Archive",
                "canonical": "/api/v1/staff/products/<slug>/archive/",
                "legacy": "",
                "view": "myapp.api.views.AdminProductArchiveApi",
                "drf": True,
                "status": "canonical",
                "notes": "Force-unpublish one currently active product.",
            },
        ],
    },
    {
        "group": "Wave 4: NewebPay Mock",
        "routes": [
            {
                "name": "Buyer NewebPay Payment",
                "canonical": "/api/v1/me/orders/<order_id>/newebpay-payment/",
                "legacy": "",
                "view": "myapp.api.views.BuyerNewebpayPaymentApi",
                "drf": True,
                "status": "canonical",
                "notes": "Mock NewebPay payment create/read endpoints used for PoC testing.",
            },
            {
                "name": "NewebPay Payment Callback",
                "canonical": "/api/v1/integrations/newebpay/payment/callback/",
                "legacy": "",
                "view": "myapp.api.views.NewebpayPaymentCallbackApi",
                "drf": True,
                "status": "canonical",
                "notes": "Mock payment callback/webhook endpoint for transaction status updates.",
            },
        ],
    },
    {
        "group": "Wave 5: NewebPay Sandbox Scaffold",
        "routes": [
            {
                "name": "Buyer NewebPay Sandbox Payment Prepare",
                "canonical": "/api/v1/me/orders/<order_id>/newebpay-payment/sandbox/",
                "legacy": "",
                "view": "myapp.api.views.BuyerNewebpaySandboxPaymentPrepareApi",
                "drf": True,
                "status": "canonical",
                "notes": "Prepare official NewebPay MPG sandbox form payload from an existing order.",
            },
            {
                "name": "NewebPay Sandbox Payment Callback",
                "canonical": "/api/v1/integrations/newebpay/payment/sandbox/callback/",
                "legacy": "",
                "view": "myapp.api.views.NewebpaySandboxPaymentCallbackApi",
                "drf": True,
                "status": "canonical",
                "notes": "Verify TradeSha and decrypt TradeInfo from the official NewebPay sandbox callback.",
            },
        ],
    },
]
