# Generated by Django 6.0.3 on 2026-06-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_banner_cart_communitypost_communityreply_mediaasset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='banner',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
