# Generated by Django 6.0.3 on 2026-06-04 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_banner_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_audit_logs',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NewebpayStoreMapSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_username_snapshot', models.CharField(blank=True, max_length=150)),
                ('selection_token', models.CharField(max_length=120, unique=True)),
                ('merchant_order_no', models.CharField(db_index=True, max_length=64)),
                ('pickup_store_brand', models.CharField(blank=True, max_length=50)),
                ('pickup_store_brand_label', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='prepared', max_length=50)),
                ('store_id', models.CharField(blank=True, max_length=50)),
                ('store_name', models.CharField(blank=True, max_length=255)),
                ('store_address', models.CharField(blank=True, max_length=500)),
                ('store_type', models.CharField(blank=True, max_length=100)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('callback_url', models.CharField(blank=True, max_length=500)),
                ('return_url', models.CharField(blank=True, max_length=500)),
                ('gateway_return_url', models.CharField(blank=True, max_length=500)),
                ('plain_params', models.JSONField(blank=True, default=dict)),
                ('form_fields', models.JSONField(blank=True, default=dict)),
                ('reply_payload', models.JSONField(blank=True, default=dict)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newebpay_store_map_selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'newebpay_store_map_selections',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
