# Generated by Django 6.0.3 on 2026-06-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='primary_image_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
